#!name=Block YouTube Ads
#!desc=for Shadowrocket

# > Feature
# 删除 瀑布流、视频、搜索中出现的广告和Shorts
# 删除 Shorts 内的视频广告
# 删除 底部 上传 按钮
# 增加 画中画(PIP), 后台播放 (Beta)
# 增加 自动翻译 (Thanks @VirgilClyne)

# > Note
# 广告信息会有遗漏，可能偶现广告
# 该模块已足够全面，无需其他规则混用，防止重写规则被破坏
# 不支持 Mock 的客户端可以用 reject-200/reject-img 替代

# > Credit 
# @Choler & @DivineEngine & @app2smile @Maasea

[Script]
youtube = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting)\?,requires-body=1,binary-body-mode=1,max-size=3145728,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.js

[URL Rewrite]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad - REJECT-IMG

[MITM]
hostname = %APPEND% youtubei.googleapis.com, *.googlevideo.com
